DOWNLOADER:
  MAX_WORKERS: 8 # Number of parallel downloads -> depends on your CPU cores

DIRECTORIES:
  IMAGE_DIR: a_images
  DATABASE_DIR: b_database
  UPLOAD_DIR: c_upload # in case you want to save the uploaded new images
  CSV_FILE: facescrub_metadata.csv
  LOG_DIR: logs


DATABASE:
  QDRANT_PATH: qdrant_db
  COLLECTION_NAME: facescrub_faces

MODEL:
  MODEL_IMAGE_SIZE: 160 # DONT CHANGE
  resnet: InceptionResnetV1 # DONT CHANGE
  EMBEDDING_DIM: 512 # DONT CHANGE
  device: cpu

APP:
  DUPLICATE_THRESHOLD: 0.55 # 1: identical, 0: totally different
  EVAL_NUM_PAIRS: 2000
  HOST: 127.0.0.1 # CHANGE TO 0.0.0.0 IF USING DOCKER